/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/measure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Measure */
        post: operations["measure_v1_measure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_measure_v1_measure_post */
        Body_measure_v1_measure_post: {
            capture_type: components["schemas"]["CaptureType"];
            /** Image */
            image: string;
            /** Reference Type */
            reference_type: string;
        };
        /**
         * CaptureType
         * @enum {string}
         */
        CaptureType: "left_fingers" | "left_thumb" | "right_fingers" | "right_thumb";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Model Version */
            model_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "not_ready";
        };
        /** MeasureResponse */
        MeasureResponse: {
            capture_type: components["schemas"]["CaptureType"];
            /**
             * Chart Id
             * @default platform-default
             * @constant
             */
            chart_id: "platform-default";
            /**
             * Chart Version
             * @default 1
             * @constant
             */
            chart_version: "1";
            /** Measurements */
            measurements: components["schemas"]["NailMeasurement"][];
            /** Model Version */
            model_version: string;
            /** Processing Ms */
            processing_ms: number;
            /** Quality Issues */
            quality_issues: components["schemas"]["QualityIssue"][];
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "retake";
        };
        /** NailMeasurement */
        NailMeasurement: {
            /** Alternate Size */
            alternate_size: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Contour */
            contour: [
                number,
                number
            ][];
            /**
             * Digit
             * @enum {string}
             */
            digit: "thumb" | "index" | "middle" | "ring" | "pinky";
            /** Projected Width Mm */
            projected_width_mm: number;
            /** Recommended Size */
            recommended_size: string;
            /** Uncertainty Mm */
            uncertainty_mm: number;
        };
        /** QualityIssue */
        QualityIssue: {
            code: components["schemas"]["QualityIssueCode"];
            /** Correction */
            correction: string;
            /** Message */
            message: string;
        };
        /**
         * QualityIssueCode
         * @enum {string}
         */
        QualityIssueCode: "REFERENCE_MISSING" | "REFERENCE_INVALID" | "BLUR" | "GLARE" | "ANGLE_TOO_STEEP" | "NAIL_CROPPED" | "NAIL_OCCLUDED" | "WRONG_NAIL_COUNT" | "UNSUPPORTED_NAIL_CONDITION" | "LOW_CONFIDENCE" | "OUTSIDE_DEFAULT_CHART";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    measure_v1_measure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_measure_v1_measure_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
